[workspace]
resolver = "2"
members = [
    "crates/boot-shared",
    "crates/boot-usb",
    "crates/boot-display",
    "crates/boot-core",
    "crates/golden",
    "crates/golden-fakeapp",
    "crates/appstub",
    "crates/worker",
    "crates/trampoline",
    "crates/migrator",
]

[profile.release]
codegen-units = 1
debug = 1
lto = true
opt-level = "z"
