[package]
name = "benchvolt-poc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
reducto = { git = "https://github.com/jvanderberg/reducto", rev = "9a3543b59e5241002f2034e7a6098ed9ded7b1aa" }

[target.'cfg(target_arch = "arm")'.dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
display-interface-spi = "0.4.1"
embedded-graphics = "0.8.2"
embedded-hal = "0.2.7"
heapless = "0.8.0"
mipidsi = "0.7.1"
panic-halt = "1.0.0"
stm32f0xx-hal = { version = "0.18.0", features = ["rt", "stm32f070xb"] }
stm32-usbd = "0.8.0"
usb-device = "0.3.2"
usbd-serial = "0.2.2"

[profile.release]
codegen-units = 1
debug = 1
lto = true
opt-level = "s"
